### ISSUE TITLE
Song names with slashes fail to download

### ISSUE THREAD

**Issue by saltedcoffii** [microsockss/free-mp3-download-cli#4]
Song names with slashes fail to download. An error then appears:
```
Traceback (most recent call last):
  File "./main.py", line 262, in <module>
    album()
  File "./main.py", line 137, in album
    download_track(track["id"], data["id"])
  File "./main.py", line 91, in download_track
    with open(
FileNotFoundError: [Errno 2] No such file or directory: 'Halsey - Manic/10 - Finally // beautiful stranger.flac'
```

**Comment by ethanbarclay** [comment]
Hi, the error with downloading flac files seems to be due to an update in
free-mp3-download's servers. I'll try to patch this and also make it so you
can download songs with slashes in them.

Thanks for informing me,
Ethan
